theme: jekyll-theme-minimal

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

author:
  name     : "Pooria Yaghini"
  avatar   : "/assets/images/pooria.jpg"
  bio      : "TBD"
  location : "CA, USA"

title: "Pooria Yaghini"
subtitle: "Version 2.0"
description: "This Hopepage shares some of my projects' informations."

repository: "https://github.com/pyaghini"


logo: "/assets/images/logo.png"
#show_downloads: "true"
#google_analytics: [Your Google Analytics tracking ID]

minimal_mistakes_skin: "contrast" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

#teaser: /assets/images/500x300.png



masthead_title: "My Custom Title"

